services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - ./wp_data:/var/www/html

  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
    volumes:
      - ./db_data:/var/lib/mysql

volumes:
  wp_data:
  db_data:
